import { DataSeries, Prisma } from "@prisma/client";
import dataFieldArray from "./lib/dataSeriesDataFieldNames.json";

/** An object that implements the AccessControlled interface can be checked with the accessChecker function. */
export interface AccessControlled {
  author: { id: string, username: string },
  editors: { id: string, username: string }[],
  viewers: { id: string, username: string }[],
  editGroups: { id: string, name: string, users: { id: string, username: string }[] }[],
  viewGroups: { id: string, name: string, users: { id: string, username: string }[] }[],
};

/** Enum for the different access levels returned by the accessChecker function. */
export enum AccessLevel {
  None = "",
  View = "VIEW",
  Edit = "EDIT",
  Author = "AUTHOR",
  Admin = "ADMIN",
};

export enum ClientError {
  AccessDenied = "You either don't have access to this entry or are trying to edit an entry that doesn't exist",
  BadSession = "Bad session cookie; you have been logged out. Please log in and try again.",
  IllegalParent = "You are trying to connect this object to a parent you don't have access to or that doesn't exist",
  StaleData = "Stale data; please refresh and try again",
};

/** The format of the data needed to create new roadmap metadata. */
export type MetaRoadmapInput = Omit<
  Prisma.MetaRoadmapCreateInput,
  'id' | 'createdAt' | 'updatedAt' | 'author' | 'editors' |
  'viewers' | 'editGroups' | 'viewGroups' | 'comments' | 'links' |
  'roadmapVersions' | 'parentRoadmap' | 'childRoadmaps'
> & {
  links?: { url: string, description?: string }[] | undefined;
  // Accepts lists of UUIDs for all of the following, to link them to the roadmap (optional)
  editors?: string[] | undefined;
  viewers?: string[] | undefined;
  editGroups?: string[] | undefined;
  viewGroups?: string[] | undefined;
  // UUID for the parent meta roadmap (if any)
  parentRoadmapId?: string | undefined;
};

/** The format of the data needed to create a new roadmap version. */
export type RoadmapInput = Omit<
  Prisma.RoadmapCreateInput,
  'id' | 'createdAt' | 'updatedAt' | 'goals' | 'author' | 'editors' |
  'viewers' | 'editGroups' | 'viewGroups' | 'comments' | 'metaRoadmap' | 'version'
> & {
  // Accepts lists of UUIDs for all of the following, to link them to the roadmap (optional)
  editors?: string[] | undefined;
  viewers?: string[] | undefined;
  editGroups?: string[] | undefined;
  viewGroups?: string[] | undefined;
  // UUID for the meta roadmap this roadmap belongs to
  metaRoadmapId: string;
  // Used in API to inherit the goals with the given IDs from other roadmaps
  inheritFromIds?: string[] | null | undefined;
  // Version numbers are assigned by the API
};

/** The format of the data needed to create a new goal. */
export type GoalInput = Omit<
  Prisma.GoalCreateInput,
  'id' | 'createdAt' | 'updatedAt' | 'roadmap' | 'author' | 'dataSeries' | 'links' | 'comments' | 'actions'
> & {
  // This will be turned into an actual dataSeries object by the API
  // The expected input is a stringified array of floats
  dataSeries: string[];
  // The unit of measurement for the data series
  dataUnit: string;
  dataScale?: string | undefined;
  links?: { url: string, description?: string }[] | undefined;
};

/** The format of the data needed to create a new action. */
export type ActionInput = Omit<
  Prisma.ActionCreateInput,
  'id' | 'createdAt' | 'updatedAt' | 'goal' | 'author' | 'notes' | 'links' | 'comments'
> & {
  links?: { url: string, description?: string }[] | undefined;
  // UUID for the goal this action belongs to
  goalId: string;
};

/** A type with only the data fields of the data series object. Not dynamic, so might need to be updated if the data series object changes. */
export type DataSeriesDataFields = Omit<
  DataSeries,
  'author' | 'unit' | 'scale' | 'id' | 'createdAt' | 'updatedAt' |
  'editors' | 'viewers' | 'editGroups' | 'viewGroups' | 'authorId' | 'goalId'
>;

/** An array containing the keys of the actual data fields in the data series object. Generated by the getDataSeriesValueFieldNames script at build time. */
export const dataSeriesDataFieldNames = dataFieldArray as (keyof DataSeriesDataFields)[];